// Recovered Cursor Projects client unit. Not original TypeScript.
// shippedPath: out/vs/workbench/workbench.desktop.main.js
// kind: named-module
// name: agentStoreScopePaths.js
// byteRange: [16616483, 16619971)
// beautified: false
// truncated: false
j({"agentStoreScopePaths.js"(){"use strict";xh(),En(),Mi(),mi(),An(),qe(),ni(),ry(),uSd(),iYs=6e4,rYs=kp("agentStorePathResolutionService"),m4i=class{constructor(e,t,n){this.commandService=e,this.workspaceContextService=t,this.agentRepositoryService=n}async resolveFileUri(e){return TAf(this.commandService,this.workspaceContextService,e,t=>this.isProjectStore(t))}isProjectStore(e){const t=this.agentRepositoryService.getAgentHeader(e);if(t===void 0)return!1;const n=t.subagentParentId;return wAf({header:t,parentHeader:n===void 0||n.length===0?void 0:this.agentRepositoryService.getAgentHeader(n)})}},m4i=__decorate([__param(0,Nn),__param(1,Gn),__param(2,U_)],m4i),dn(rYs,m4i,2,1)}});function EAf(e){const t=e.subagentTypeName===x3e||e.subagentTypeName===z2,n=e.isTaskOrigin===!0&&e.currentTurnIsDirectUserEntered===!0&&e.parentComposerId!==void 0&&e.parentComposerId===e.owningProjectAgentId;return(t||n)&&e.parentComposerId!==void 0&&e.parentComposerId.trim().length>0&&!e.isSimulatedTurn&&!e.isBestOfNTurn}function xAf(e){return!e.inboxGateEnabled||!EAf(e)?"none":e.wakeEnabled&&e.parentComposerId===e.owningProjectAgentId?"background-task":"file-inbox"}function IAf(e){const t=e.turnId?.trim()||e.runId.trim(),n=`${KRc({parentId:e.parentComposerId,childId:e.childComposerId})}:${t}`,r=(e.status==="success"?e.resultText:e.errorText)?.trim();return{conversationId:e.parentComposerId,id:e.runId,groupKey:n,source:"interactive-child",payload:{composerId:e.parentComposerId,taskId:n,kind:"subagent",status:e.status,title:e.title,...r!==void 0&&r.length>0?{detail:r}:{},reason:"task_finished",subagentId:e.childComposerId,...e.currentTurnIsDirectUserEntered?{notificationContext:"user_driven_interactive_child"}:{}}}}function AAf(e){const t=KRc({parentId:e.parentComposerId,childId:e.childComposerId}),n=YRc({routeId:t,runId:e.runId,finishedAt:e.pathTimestamp??e.finishedAt}),i=e.resultText?.trim().slice(0,aYs),r=e.errorText?.trim().slice(0,cYs),s={source:_pn,childComposerId:e.childComposerId,runId:e.runId,routeId:t,status:e.status,finishedAt:e.finishedAt.toISOString(),...r!==void 0&&r.length>0?{errorCode:r}:{},...i!==void 0&&i.length>0?{resultText:i}:{}};return{relPath:n,contents:`${JSON.stringify(s)}
`}}function sYs(e,t){return Se.joinPath(Se.file(e),...t.split("/"))}async function RAf(e,t){const n=AAf(t.turn);await e.writeFile(sYs(t.parentStoreFilesDir,n.relPath),fi.fromString(n.contents))}async function DAf(e,t){const n=tAm({parentId:t.parentComposerId,childId:t.childBcId}),i=YRc({routeId:n,runId:t.runId,finishedAt:t.finishedAt}),s=t.detail?.trim()?.slice(0,t.status==="success"?aYs:cYs),o={source:_pn,childBcId:t.childBcId,runId:t.runId,routeId:n,routeKind:"child_turn",status:t.status,finishedAt:t.finishedAt.toISOString(),...s!==void 0&&s.length>0?t.status==="success"?{resultText:s}:{errorCode:s}:{}};return await e.writeFile(sYs(t.parentStoreFilesDir,i),fi.fromString(`${JSON.stringify(o)}
`)),i}async function hSd(e,t){let n;try{n=(await e.resolve(sYs(t.parentStoreFilesDir,fut.replace(/\/$/,"")))).children??[]}catch(s){if(s instanceof Error&&DP(s)===1)return;throw s}const i=n.filter(s=>!s.isDirectory).map(s=>`${fut}${s.name}`).filter(s=>iAm(s.slice(fut.length))||XRc(s)).filter(s=>t.cursor===void 0||s>t.cursor).sort(),r=i[i.length-1];if(r!==void 0)return{entryRelPaths:i,maxKey:r}}function pSd(e,t){const n=e?.trim();return t===void 0||t.length===0?e:n!==void 0&&n.length>0?`${n}

${t}`:t}function MAf(e,t){return e===void 0||e<t?t:void 0}var oYs,aYs,cYs,lYs=
