// Recovered Cursor Projects client unit. Not original TypeScript.
// shippedPath: out/vs/workbench/workbench.glass.main.js
// kind: named-module
// name: agentStoreScopePaths.js
// byteRange: [17739470, 17742957)
// beautified: false
// truncated: false
O({"agentStoreScopePaths.js"(){"use strict";Yc(),ri(),Pr(),ls(),Pn(),_t(),yr(),ac(),H9p(),YAa=6e4,pmi=Cu("agentStorePathResolutionService"),jBr=class{constructor(t,e,n){this.commandService=t,this.workspaceContextService=e,this.agentRepositoryService=n}async resolveFileUri(t){return OQy(this.commandService,this.workspaceContextService,t,e=>this.isProjectStore(e))}isProjectStore(t){const e=this.agentRepositoryService.getAgentHeader(t);if(e===void 0)return!1;const n=e.subagentParentId;return UBr({header:e,parentHeader:n===void 0||n.length===0?void 0:this.agentRepositoryService.getAgentHeader(n)})}},jBr=__decorate([__param(0,tr),__param(1,fr),__param(2,al)],jBr),vn(pmi,jBr,2,1)}});function FQy(t){const e=t.subagentTypeName===aK||t.subagentTypeName===II,n=t.isTaskOrigin===!0&&t.currentTurnIsDirectUserEntered===!0&&t.parentComposerId!==void 0&&t.parentComposerId===t.owningProjectAgentId;return(e||n)&&t.parentComposerId!==void 0&&t.parentComposerId.trim().length>0&&!t.isSimulatedTurn&&!t.isBestOfNTurn}function BQy(t){return!t.inboxGateEnabled||!FQy(t)?"none":t.wakeEnabled&&t.parentComposerId===t.owningProjectAgentId?"background-task":"file-inbox"}function UQy(t){const e=t.turnId?.trim()||t.runId.trim(),n=`${h1u({parentId:t.parentComposerId,childId:t.childComposerId})}:${e}`,r=(t.status==="success"?t.resultText:t.errorText)?.trim();return{conversationId:t.parentComposerId,id:t.runId,groupKey:n,source:"interactive-child",payload:{composerId:t.parentComposerId,taskId:n,kind:"subagent",status:t.status,title:t.title,...r!==void 0&&r.length>0?{detail:r}:{},reason:"task_finished",subagentId:t.childComposerId,...t.currentTurnIsDirectUserEntered?{notificationContext:"user_driven_interactive_child"}:{}}}}function jQy(t){const e=h1u({parentId:t.parentComposerId,childId:t.childComposerId}),n=p1u({routeId:e,runId:t.runId,finishedAt:t.pathTimestamp??t.finishedAt}),i=t.resultText?.trim().slice(0,ZAa),r=t.errorText?.trim().slice(0,JAa),s={source:AWn,childComposerId:t.childComposerId,runId:t.runId,routeId:e,status:t.status,finishedAt:t.finishedAt.toISOString(),...r!==void 0&&r.length>0?{errorCode:r}:{},...i!==void 0&&i.length>0?{resultText:i}:{}};return{relPath:n,contents:`${JSON.stringify(s)}
`}}function XAa(t,e){return Ve.joinPath(Ve.file(t),...e.split("/"))}async function $Qy(t,e){const n=jQy(e.turn);await t.writeFile(XAa(e.parentStoreFilesDir,n.relPath),br.fromString(n.contents))}async function WQy(t,e){const n=ZDb({parentId:e.parentComposerId,childId:e.childBcId}),i=p1u({routeId:n,runId:e.runId,finishedAt:e.finishedAt}),s=e.detail?.trim()?.slice(0,e.status==="success"?ZAa:JAa),o={source:AWn,childBcId:e.childBcId,runId:e.runId,routeId:n,routeKind:"child_turn",status:e.status,finishedAt:e.finishedAt.toISOString(),...s!==void 0&&s.length>0?e.status==="success"?{resultText:s}:{errorCode:s}:{}};return await t.writeFile(XAa(e.parentStoreFilesDir,i),br.fromString(`${JSON.stringify(o)}
`)),i}async function q9p(t,e){let n;try{n=(await t.resolve(XAa(e.parentStoreFilesDir,lNt.replace(/\/$/,"")))).children??[]}catch(s){if(s instanceof Error&&VD(s)===1)return;throw s}const i=n.filter(s=>!s.isDirectory).map(s=>`${lNt}${s.name}`).filter(s=>e3b(s.slice(lNt.length))||m1u(s)).filter(s=>e.cursor===void 0||s>e.cursor).sort(),r=i[i.length-1];if(r!==void 0)return{entryRelPaths:i,maxKey:r}}function V9p(t,e){const n=t?.trim();return e===void 0||e.length===0?t:n!==void 0&&n.length>0?`${n}

${e}`:e}function HQy(t,e){return t===void 0||t<e?e:void 0}var QAa,ZAa,JAa,eRa=
