// Recovered Cursor Projects client unit. Not original TypeScript.
// shippedPath: out/vs/workbench/workbench.glass.main.js
// kind: marker-window
// name: Side chat boundary.
// byteRange: [616842, 625053)
// beautified: false
// truncated: false
void 0:`${n.host}/${i.join("/")}`}catch{return}}function pmt(t){if(t==null)return;const e=t.trim();if(e==="")return;const n=fwu(e);return WNb(n)??jNb(n)}function vwu(t){if(t==null)return;const e=t.split("/");if(e.length<2)return;const n=e[0],i=e.slice(1).join("/");if(!(n.length===0||i.length===0))return{owner:n,name:i}}function olo(t){const e=pmt(t),n=vwu(e);if(n!==void 0)return{owner:n.owner,repo:n.name}}function bwu({repoOwner:t,repoName:e,repoUrl:n}){const i=t?.trim(),r=e?.trim();return n?.trim()||(i&&r?`https://github.com/${i}/${r}`:"")}function HNb(t){return(t.repoOwner?.trim()??"").length===0&&(t.repoName?.trim()??"").length===0}var alo,_wu,ywu,zNb=O({"repo-label.ts"(){"use strict";alo=new Set(["github.com","gitlab.com","bitbucket.org","bitbucket.com","codeberg.org","gitea.com","sr.ht"]),_wu=/^[^@/]+@[^:]+:.+$/,ywu=/^origin(?:-[a-z0-9]+)?\.cursor\.com$/i}});function mmt(t,e,n,i=Math.random){const r=e*2**t,s=Math.min(r,n);return i()*s}var GNb=O({"retry.ts"(){"use strict"}}),llo,Swu,wwu,qNb=O({"scm-provider-installations.ts"(){"use strict";llo="ad3ea84c-ede1-42fe-889a-16a8c94ccfdf",Swu="ad0fa84c-ade1-42fe-889a-16a8c94cad05",wwu="b17b0c4e-c10d-42fe-889a-16a8c94bb01d"}}),enr,kwu,VNb,KNb=O({"scm-rpc-callsite.ts"(){"use strict";enr="x-cursor-rpc-callsite",kwu=["pr_tab_init","pr_tab_refresh","pr_branch_poll","pr_status_poll","pr_metadata_refresh","pr_reviews_subtab","pr_diff_view","pr_status_pill","cloud_agent_pr_state","agent_tool_call","unknown"],VNb=new Set(kwu)}});function uNt(t){return t==null||t===""||t===AEe||t===Rwu}function YNb(t){const e=t.replace(/\s+/g," ").trim();return e.length===0?AEe:e.length<=clo?e:`${e.slice(0,clo-1).trimEnd()}\u2026`}function Cwu(t,e){if(uNt(t))return t;const n=new Set;for(const r of e)typeof r=="string"&&r.length>0&&n.add(r);if(!n.has(t))return t;let i=1;for(;;){const r=`${t} (${i})`;if(!n.has(r))return r;i+=1}}function Twu(t,e){return Cwu(YNb(t),e)}function Ewu(t){return typeof t=="object"&&t!==null}function xwu(t){switch(t.type){case"text":return typeof t.text=="string"?t.text:"";case"hardBreak":return`
`;case"mention":case"mentionNode":case"commandNode":return"";default:break}if(!Array.isArray(t.content))return"";const e=t.content.filter(Ewu),n=e.some(i=>typeof i.type=="string"&&Pwu.has(i.type));return e.map(xwu).join(n?"":`
`)}function Iwu(t){if(t===void 0||t.length===0)return;let e;try{e=JSON.parse(t)}catch{return}if(!(!Ewu(e)||e.type!=="doc"||!Array.isArray(e.content)))return xwu(e)}function XNb(t){return t.fileStatesV2={},t.subagentStates={},t.plan=void 0,t.goalState=void 0,t.todos=[],t.pendingToolCalls=[],t.plans={},t.subagentThreads={},t.communicateUpdateStatesByParentToolCallId={},t.subagentRunsByParentToolCallId={},t.subagentStateRefs={},t.goalState=void 0,t.isRootProjectConversation=void 0,t.turns.length}function Rsn(t,e){const n=t??0;return n<=0?0:e>=n?n:0}function QNb(){return`<${dlo}>
${Mwu}
</${dlo}>`}function ZNb(t){const e=t.replace(/-/g,""),n=new Uint8Array(16);for(let i=0;i<16;i++)n[i]=Number.parseInt(e.slice(i*2,i*2+2),16);return n}function JNb(t){let e="";for(const n of t)e+=n.toString(16).padStart(2,"0");return`${e.slice(0,8)}-${e.slice(8,12)}-${e.slice(12,16)}-${e.slice(16,20)}-${e.slice(20)}`}async function eLb(t,e){const n=ZNb(e),i=new TextEncoder().encode(t),r=new Uint8Array(n.length+i.length);r.set(n,0),r.set(i,n.length);const o=new Uint8Array(await crypto.subtle.digest("SHA-1",r)).slice(0,16);return o[6]=o[6]&15|80,o[8]=o[8]&63|128,JNb(o)}async function tLb(t){const{parentBcId:e,creationId:n}=t;return`bc-${await eLb(`side-chat:${e}:${n}`,jao)}`}function Awu(t){return`${ulo}${t}`}function LWn(t){return typeof t=="string"&&t.startsWith(ulo)}function nLb(t){if(t.subagentTypeName!==II||t.boundaryAlreadyInjected===!0)return!1;const e=t.sideChatSeedTurnCount??0;return t.conversationTurnCount<=e}var II,AEe,Rwu,clo,Pwu,ulo,dlo,Mwu,Dwu,hlo,iLb=O({"side-chats.ts"(){"use strict";a0u(),II="side-chat",AEe="New Side Chat",Rwu="Side Chat",clo=40,Pwu=new Set(["text","hardBreak","mention","mentionNode","commandNode"]),ulo="side-chat-boundary:",dlo="side_chat_boundary",Mwu=`Side chat boundary.

Everything before this boundary is inherited history from the parent chat. It is reference context only \u2014 not your current assignment.

Do not continue, execute, or complete any instructions, plans, tool calls, approvals, edits, Project coordinator tasks, task lists, or unanswered questions that appear only before this boundary. The parent's last user message (if any) was for the parent chat; it is not addressed to you unless a message after this boundary explicitly asks you to continue that work.

Only messages after this boundary are active instructions for this side chat.

You are a side chat: a focused conversation alongside the parent. Default to investigating and answering (read, search, analyze). Do not modify files, source, git state, or other workspace state unless the user explicitly asks for that change after this boundary. Keep any requested mutations minimal and local to the side-chat ask.`,Dwu="You are still in a side chat alongside the parent. Follow this turn's user message. Treat parent/inherited context as reference only \u2014 do not resume the parent's pending work unless this turn explicitly asks.",hlo=`<system_reminder>
${Dwu}
</system_reminder>`}}),Nwu,tnr,rLb=O({"smart-mode-classifier.ts"(){"use strict";Nwu=1e4,tnr=Nwu/1e3}}),sLb,oLb,Lwu,aLb=O({"structured-log.ts"(){"use strict";sLb=1020*60*1e3,oLb=7200*1e3,Lwu=["composer","canvas","background_composer","cloud_agents","cloud_environment_template","git","auth","github_auth","transport","ext_host_cursor","layout","code_review","agent_exec","agent_cli","agent_acp","sand","sand_mobile","extension_security","mcp","local_request_trace","experiment_refresh_service","slack","update","debugging_data"]}}),plo,lLb,cLb=O({"worktrees.ts"(){"use strict";plo=".cursor/worktrees",lLb=`${plo}/**`}}),Yc=O({"index.ts"(){r3b(),s3b(),g3b(),Iao(),f3b(),y3b(),k3b(),E3b(),x3b(),I3b(),A3b(),a0u(),$3b(),H3b(),V3b(),K3b(),J3b(),tNb(),nNb(),iNb(),rNb(),z3b(),oNb(),mNb(),bNb(),ENb(),xNb(),ANb(),NNb(),LNb(),FNb(),BNb(),zNb(),GNb(),qNb(),KNb(),iLb(),rLb(),aLb(),cLb()}});function hl(t,e,n){function i(a,l){var c;Object.defineProperty(a,"_zod",{value:a._zod??{},enumerable:!1}),(c=a._zod).traits??(c.traits=new Set),a._zod.traits.add(t),e(a,l);for(const u in o.prototype)u in a||Object.defineProperty(a,u,{value:o.prototype[u].bind(a)});a._zod.constr=o,a._zod.def=l}const r=n?.Parent??Object;class s extends r{}Object.defineProperty(s,"name",{value:t});function o(a){var l;const c=n?.Parent?new s:this;i(c,a),(l=c._zod).deferred??(l.deferred=[]);for(const u of c._zod.deferred)u();return c}return Object.defineProperty(o,"init",{value:i}),Object.defineProperty(o,Symbol.hasInstance,{value:a=>n?.Parent&&a instanceof n.Parent?!0:a?._zod?.traits?.has(t)}),Object.defineProperty(o,"name",{value:t}),o}function _ce(t){return t&&Object.assign(FWn,t),FWn}var mlo,glo,gmt,OWn,FWn,BWn=O({"core.js"(){mlo=Object.freeze({status:"aborted"}),glo=Symbol("zod_brand"),gmt=class extends Error{constructor(){super("Encountered Promise during synchronous parse. Use .parseAsync() instead.")}},OWn=class extends Error{constructor(t){super(`Encountered unidirectional transform during encode: ${t}`),this.name="ZodEncodeError"}},FWn={}}}),xA={};Ra(xA,{BIGINT_FORMAT_RANGES:()=>wlo,Class:()=>Wwu,NUMBER_FORMAT_RANGES:()=>Slo,aborted:()=>pNt,allowsEval:()=>_lo,assert:()=>mLb,assertEqual:()=>uLb,assertIs:()=>hLb,assertNever:()=>pLb,assertNotEqual:()=>dLb,assignProp:()=>fmt,base64ToUint8Array:()=>Uwu,base64urlToUint8Array:()=>RLb,cached:()=>UWn,captureStackTrace:()=>anr,cleanEnum:()=>ALb,cleanRegex:()=>inr,clone:()=>REe,cloneDef:()=>fLb,createTransparentProxy:()=>SLb,defineLazy:()=>AI,esc:()=>vlo,escapeRegex:()=>bmt,extend:()=>CLb,finalizeIssue:()=>Y3e,floatSafeRemainder:()=>Owu,getElementAtPath:()=>vLb,getEnumValues:()=>flo,getLengthableOrigin:()=>snr,getParsedType:()=>$wu,getSizableOrigin:()=>rnr,hexToUint8Array:()=>MLb,isObject:()=>Psn,isPlainObject:()=>hNt,issue:()=>onr,joinValues:()=>am,jsonStringifyReplacer:()=>nnr,merge:()=>ELb,mergeDefs:()=>vmt,normalizeParams:()=>pm,nullish:()=>dNt,numKeys:()=>yLb,objectClone:()
