// Recovered Cursor Projects client unit. Not original TypeScript.
// shippedPath: out/vs/workbench/workbench.glass.main.js
// kind: named-module
// name: AgentTranscriptMcpToolCallLine.js
// byteRange: [12879310, 12882119)
// beautified: false
// truncated: false
O({"AgentTranscriptMcpToolCallLine.js"(){"use strict";vF(),Zdh(),ehh(),fhh(),TIe(),a$e(),CIe(),_N(),aJo(),yse(),PL(),hph=`

`}});import{jsx as w9t,jsxs as qxr}from"./react-runtime/react/esm-jsx-runtime-production.js";import{c as MG_}from"./react-runtime/react/esm-compiler-runtime-production.js";function cJo(t){const e=MG_(31),{title:n,detail:i,overview:r,onOpen:s,buildControls:o}=t,l=(i===void 0?"ide":i)==="glass",c=l&&s!==void 0,u=!l&&!!r,d=!l&&s!==void 0,h=!l&&o!==void 0,p=d||h,g=u||p;let v;e[0]===Symbol.for("react.memo_cache_sentinel")?(v={className:"ui-2lah0s"},e[0]=v):v=e[0];const b=v.className;let _;e[1]===Symbol.for("react.memo_cache_sentinel")?(_={className:"ui-78zum5 ui-6s0dn4 ui-ehausa ui-euugli ui-98rzlu ui-f6zju3 ui-cnij5n"},e[1]=_):_=e[1];const y=_;let S;e[2]===Symbol.for("react.memo_cache_sentinel")?(S={className:"ui-78zum5 ui-dt5ytf ui-ehausa ui-1meegvc ui-1xlntvz ui-4pf3lq"},e[2]=S):S=e[2];const k=S;let C;e[3]===Symbol.for("react.memo_cache_sentinel")?(C={className:"ui-78zum5 ui-6s0dn4 ui-13a6bvl ui-pkkfsy ui-1a02dak"},e[3]=C):C=e[3];const T=C;let E;e[4]===Symbol.for("react.memo_cache_sentinel")?(E={className:"ui-8kmwxx ui-4b2ntj ui-1qdabqz"},e[4]=E):E=e[4];const I=E;let A;e[5]===Symbol.for("react.memo_cache_sentinel")?(A={className:"ui-78zum5 ui-dt5ytf ui-xhr3t ui-1iyjqo2 ui-s83m0k ui-dl72j9 ui-euugli"},e[5]=A):A=e[5];const P=A;let N;e[6]===Symbol.for("react.memo_cache_sentinel")?(N={className:"ui-1ja60sm ui-19aaqeu"},e[6]=N):N=e[6];const L=N;let B;e[7]===Symbol.for("react.memo_cache_sentinel")?(B=w9t(rn,{...L,color:"secondary",children:"Created Plan"}),e[7]=B):B=e[7];let F;e[8]!==n?(F=qxr("div",{className:P.className,style:P.style,children:[B,w9t(rn,{color:"primary","data-testid":"composer-plan-filename",rootStyle:pph.summaryTitle,size:"lg",truncate:!0,weight:"medium",children:n})]}),e[8]=n,e[9]=F):F=e[9];const U=F,$=c?"default":"flat";let G;e[10]!==c?(G=c?w9t(Ot,{"aria-hidden":!0,className:b,color:"tertiary",name:"chevron-right",size:"base"}):null,e[10]=c,e[11]=G):G=e[11];let W;e[12]!==U||e[13]!==G?(W=qxr("div",{...y,children:[U,G]}),e[12]=U,e[13]=G,e[14]=W):W=e[14];const q=c?s:void 0;let z;e[15]!==o||e[16]!==g||e[17]!==p||e[18]!==s||e[19]!==r||e[20]!==h||e[21]!==u||e[22]!==d?(z=g?qxr("div",{...k,children:[u&&r?w9t("div",{...I,children:w9t(wC,{size:"sm",children:r})}):null,p?qxr("div",{...T,children:[d?w9t(Ln,{onClick:s,variant:"text",children:"View Plan"}):null,h?o:null]}):null]}):null,e[15]=o,e[16]=g,e[17]=p,e[18]=s,e[19]=r,e[20]=h,e[21]=u,e[22]=d,e[23]=z):z=e[23];let V;return e[24]!==g||e[25]!==$||e[26]!==W||e[27]!==q||e[28]!==z||e[29]!==n?(V=w9t(_Er,{expanded:g,expandable:!1,headerVariant:$,headerDivider:!1,header:W,headerTitle:n,onHeaderClick:q,children:z}),e[24]=g,e[25]=$,e[26]=W,e[27]=q,e[28]=z,e[29]=n,e[30]=V):V=e[30],V}var pph,mph=
